In [1]:
import numpy as np

In [2]:
import pandas as pd

### Numeric Python = >numpy

In [5]:
a = np.array([23, 34, 45])
a

array([23, 34, 45])

In [48]:
a = np.array([(23, 34, 45), (1,2,3)])
a

array([[23, 34, 45],
       [ 1,  2,  3]])

In [49]:
a.ndim

2

In [50]:
a.itemsize

8

In [51]:
a.dtype

dtype('int64')

In [52]:
a.size

6

In [53]:
a.shape

(2, 3)

In [54]:
a .reshape(3,2)

array([[23, 34],
       [45,  1],
       [ 2,  3]])

In [55]:
a

array([[23, 34, 45],
       [ 1,  2,  3]])

In [56]:
a[0,2]

45

In [57]:
a[0:,2]

array([45,  3])

In [58]:
aa = np.linspace(1, 10, 10) # even spaced numbers in the interval

In [59]:
aa

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [60]:
aa.min()

1.0

In [61]:
aa.max()

10.0

In [62]:
aa.sum()

55.0

* rows are axis 1, columns are axis 0

In [63]:
a

array([[23, 34, 45],
       [ 1,  2,  3]])

In [64]:
a.sum(axis = 0)

array([24, 36, 48])

In [65]:
a.sum(axis = 1)

array([102,   6])

* sqrt, * / + 

### Stacking

In [67]:
x = np.array([(1, 2, 3), (4, 5, 6)])
y = np.array([(7, 8, 9), (10, 11, 12)])

In [68]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
y

array([[ 7,  8,  9],
       [10, 11, 12]])

In [72]:
np.vstack((x,y)) # vertical stacking-row wise

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [73]:
np.hstack((x,y)) # stack arrays in sequence horizontally (column wise).

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

#### Pandas Series

In [75]:
list1 = [1, 2, 3]
list2 = ['a', 'b', 'c']
arr = np.array(list1)

In [90]:
ser = pd.Series(list1 , index=list2)

In [91]:
list2 * 2

['a', 'b', 'c', 'a', 'b', 'c']

In [92]:
ser * 2

a    2
b    4
c    6
dtype: int64

In [95]:
ser1 = ser + ser

In [96]:
ser1

a    2
b    4
c    6
dtype: int64

In [98]:
from numpy import random

In [99]:
np.random.seed(10)

In [101]:
df = pd.DataFrame(random.randn(3,3), ['A', 'B', 'C'], ['D', 'E', 'F'])

In [102]:
df

D         E         F
A  2.240893  1.867558 -0.977278
B  0.950088 -0.151357 -0.103219
C  0.410599  0.144044  1.454274

In [103]:
df["D"] #Series

A    2.240893
B    0.950088
C    0.410599
Name: D, dtype: float64

In [104]:
type(df["D"])

pandas.core.series.Series

In [105]:
type(df)

pandas.core.frame.DataFrame

In [107]:
df.isnull().any()

D    False
E    False
F    False
dtype: bool

In [110]:
df.drop('C')

D         E         F
A  2.240893  1.867558 -0.977278
B  0.950088 -0.151357 -0.103219

In [115]:
df.drop(columns=['F'])

D         E
A  2.240893  1.867558
B  0.950088 -0.151357
C  0.410599  0.144044